apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: nfs-server
  name: PVNAME
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: NFSSERVERIP
    path: NFSEXPORTPATH
  mountOptions:
    - vers=4
